apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: webapp-index
  labels:
    app: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-app-john
          image: fadydevops/html:pr-3
          ports:
            - containerPort: 8080