apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    run: nginx-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nginx-pod