apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    app: nginx-pod
spec:
  selector:
    app: nginx-pod
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80