apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: webapp
  labels:
    app: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-app
          image: fadydevops/game-temp:latest
          ports:
            - containerPort: 8080
